pip install coreapi
pip install coreschema
pip install Django
pip install django-cors-headers
pip install djangorestframework
pip install geopy
pip install gunicorn
pip install Pillow
pip install PyYAML
pip install whitenoise
python manage.py makemigrations
python manage.py migrate
