# Generated by Django 4.2.5 on 2023-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a driver.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
