# Generated by Django 4.2.5 on 2023-10-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_location', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
                ('two_way', models.BooleanField()),
                ('no_of_passengers', models.IntegerField()),
                ('pickup_long', models.FloatField()),
                ('pickup_lat', models.FloatField()),
                ('dest_long', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('distance', models.FloatField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
