# Generated by Django 4.2.5 on 2023-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_summary', '0003_junction_ride_pricetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsummary',
            old_name='no_of_passengers',
            new_name='no_of_passenger',
        ),
        migrations.AddField(
            model_name='ride',
            name='no_of_passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='two_way',
            field=models.BooleanField(default=False),
        ),
    ]
